Fureeous ashenvale horde
Ludovicus-Maior/WoW-Pro-Guides pull request #2054
Opened 2022-07-26 19:44 UTC by mdavidson37

Minor fixes:

- Gorat's Corpse: removed erroneous |FLY|OLD| Tag
- Small hands, Short Fuse: Blizz has renamed to Small Stature, Short Fuse
- Tweedle's Tiny Package: Blizz has renamed to Tweedle's Tiny Parcel
- The Essence of Aku'Mai: Changed to rank 1 as it is required for Loremaster achieve
- Silverwind Refuge: Fixed step to set hearth.

2022-07-27 15:16 UTC, Hendo72 commented on WoWPro_Leveling/Horde/CATA_Ashenvale.lua
> +A The Essence of Aku'Mai|QID|26890|M|11.57,35.31|ELITE|N|From Dagrun Ragehammer.|RANK|2|
Remove the ELITE tag. Not required anymore. Secondly, it should be RANK|1| not 2.

2022-07-27 15:18 UTC, Hendo72 commented on WoWPro_Leveling/Horde/CATA_Ashenvale.lua
> +h Silverwind Refuge|ACTIVE|25|M|50.43,67.16|N|At Innkeeper Chin'toka.|
I would change this to |AVAILABLE|26416|. Prevents surviving resets.

2022-07-27 15:18 UTC, Hendo72 approved these changes

2022-07-27 15:42 UTC, mdavidson37 commented
> Does the following C step not accomplish the same thing? I suggest deleting the R step and adding to the note to run to the corpse

I felt that it didn't. The quest flow is that you need to go to C and revive Gorat - who then walks to the R step location and summons Captain Elendilad for you to kill.

If you go straight to the C step there's nothing there and they are far apart enough for it to be non-obvious where to go unless you look at the quest marker. Arguably you could remove the R step and add a note to the C step to follow Gorat to kill the Captain.

2022-07-27 16:09 UTC, Cagomei requested changes
From testing these changes removing the FLY and OLD are needed. i would suggest leaving the R, and changing the C to a K with a |QO|1| for the visual of this is a named mob that needs to be killed.

2022-07-27 16:11 UTC, Cagomei approved these changes

2022-07-29 11:38 UTC, merged

2022-07-29 11:39 UTC, Ludovicus-Maior commented
@mdavidson37 Sorry for the grilling.